"""change_donations

Revision ID: 801b8c2396c2
Revises: 740ac9a45d21
Create Date: 2024-09-13 20:03:41.293933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801b8c2396c2'
down_revision = '740ac9a45d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
