"""change_int_fields

Revision ID: 85e6b122b4a9
Revises: 801b8c2396c2
Create Date: 2024-09-13 20:09:28.490156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e6b122b4a9'
down_revision = '801b8c2396c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
