"""change_name_and_constraint_ver2

Revision ID: b99e443837e3
Revises: fa85d0b61739
Create Date: 2024-09-19 14:50:41.167352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99e443837e3'
down_revision = 'fa85d0b61739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
